name: RebelsTPA
version: '1.0-SNAPSHOT'
main: rebelmythik.rebelsTPA.RebelsTPA
api-version: '1.20'
authors: [ RebelMythik, CaveRaider ]
description: Teleportation, RTP, and Home plugin

commands:
  tpa:
    permission: rtpa.tpa

  tpaccept:

  tpadeny:

  tpablock:

  tpahere:

  tpall:
    permission: rtpa.admin.tpall

  sethome:

  home:

  delhome:

  rtpareload:
    permission: rtpa.admin.reload

