name: RebelsTPA
version: '1.0-SNAPSHOT'
main: rebelmythik.rebelsTPA.RebelsTPA
api-version: '1.20'
authors: [ RebelMythik, CaveRaider ]
description: Simple teleportation plugin

commands:
  tpa:
  tpaccept:
  tpadeny:
  tpablock:
  tpahere:
  tpall:
  sethome:
  home:
  delhome:

